name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # The user's workflow mentioned ./gradlew, but we don't have the wrapper scripts.
      # We installed Gradle 8.6 globally, so we should use the global `gradle` command.
      # Also, the user's workflow didn't include setting up the settings.gradle file, which we know is needed.
      # Let's add a step to create settings.gradle before building.
      - name: Create settings.gradle
        run: echo "include ':app'" > settings.gradle

      - name: Build with Gradle
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

